import type { GlobalThemeOverrides } from "naive-ui";

const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: "#32324d",
    infoColor: "#FDF4DC",
    infoColorHover: "#FDF4DC",
    infoColorPressed: "#FDF4DC",
    warningColor: "#D9822F",
    warningColorHover: "#D9822F",
  },
  // Form: {
  //   feedbackHeightLarge: "12px",
  //   feedbackFontSizeLarge: "12px",
  //   feedbackTextColorError: "#D02B20",
  // },
  // Input: {
  //   borderHover: "1px solid #32324d",
  //   borderFocus: "1px solid #32324d",
  // },
  // InternalSelection: {
  //   borderHover: "1px solid #32324d",
  //   borderFocus: "1px solid #32324d",
  // },
  // DataTable: {
  //   fontSizeSmall: "12px",
  //   thColor: "#ffffff",
  //   loadingColor: "#d9822f",
  // },
  // Pagination: {
  //   itemColorActive: "#fff",
  //   itemBorderActive: "#fff",
  // },
  // Checkbox: {
  //   fontSizeLarge: "12px",
  //   labelLineHeight: "",
  //   colorChecked: "#d9822f",
  //   borderChecked: "1px solid #c6c6c9",
  // },
  // Dialog: {
  //   padding: 0,
  //   contentMargin: 0,
  // },
  // Empty: {
  //   textColor: "#A5A5BA",
  // },
  Menu: {
    itemColorActive: "#FDF4DC",
    itemColorActiveHover: "#FDF4DC",
    itemTextColorHorizontal: "#666687",
    itemIconColor: "#666687",
    itemTextColorActiveHorizontal: "#D9822F",
    itemIconColorActiveHorizontal: "#D9822F",
    itemTextColorHoverHorizontal: "#D9822F",
    itemIconColorHoverHorizontal: "#D9822F",
    itemTextColorActiveHover: "#D9822F",
    itemIconColorActiveHover: "#D9822F",
    itemIconColorChildActive: "#D9822F",
    itemTextColorChildActive: "#D9822F",
    itemTextColorChildActiveHover: "#D9822F",
    itemIconColorChildActiveHover: "#D9822F",
    arrowColorChildActive: "#D9822F",
    arrowColorChildActiveHover: "#D9822F",
    itemHeight: "32px",
  },
  // Layout: {
  //   textColor: "#32324d",
  // },
  // Scrollbar: {
  //   color: "#d9822f",
  //   colorHover: "#d9822f",
  // },
  // Button: {
  //   textColor: "#666687",
  //   textColorFocus: "#666687",
  //   textColorHover: "#666687",
  //   textColorPressed: "#666687",
  //   border: "1px solid #666687",
  //   borderHover: "1px solid #666687",
  //   borderFocus: "1px solid #666687",
  //   colorPrimary: "#00095B",
  //   colorHoverPrimary: "#00095B",
  //   colorFocusPrimary: "#00095B",
  //   colorPressedPrimary: "#00095B",
  //   borderHoverPrimary: "#00095B",
  //   borderPressedPrimary: "#00095B",
  //   borderFocusPrimary: "#00095B",
  //   colorDisabledPrimary: "#dcdce4",
  //   borderDisabledPrimary: "#dcdce4",
  //   textColorInfo: "#666687",
  //   textColorDisabledInfo: "#666687",
  //   textColorFocusInfo: "#666687",
  //   textColorHoverInfo: "#666687",
  //   textColorPressedInfo: "#666687",
  //   borderInfo: "1px solid #FAE7B9",
  //   borderHoverInfo: "1px solid #FAE7B9",
  //   borderFocusInfo: "1px solid #FAE7B9",
  //   fontSizeMedium: "12px",
  //   fontSizeSmall: "12px",
  //   borderRadiusMedium: "4px",
  // },
  // Badge: {
  //   fontFamily: "inherit",
  // },
  // Radio: {
  //   boxShadowActive: "inset 0 0 0 1px #C0C0CF",
  //   dotColorActive: "#d9822f",
  //   boxShadowHover: "inset 0 0 0 1px #C0C0CF",
  //   boxShadowFocus: "inset 0 0 0 1px #C0C0CF",
  // },
};

export default themeOverrides;
